version: '3.8'

services:
  # 1. NODE.JS BACKEND (API) SERVİSİ
  backend:
    build:
      context: ./server  # Nereden build edilecek
      dockerfile: Dockerfile
    container_name: survey-backend
    restart: always 
    ports:
      - "5000:5000" 
    volumes:
      - ./server/database.json:/app/database.json # Veritabanı dosyasını kalıcı yap
    networks:
      - survey-network 

  # 2. NEXT.JS FRONTEND SERVİSİ
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: survey-frontend
    restart: always
    ports:
      - "3000:3000" 
    depends_on:
      - backend 
    networks:
      - survey-network 
    environment:
      # Frontendi, backend'in iç ağdaki ismine yönlendiriyoruz
      - NEXT_PUBLIC_API_URL=http://backend:5000/api 


# Docker'ın kendi iç ağı
networks:
  survey-network:
    driver: bridge